### ISSUE TITLE
☂️ compat: tracking issue for next.js support

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2489]
part of https://github.com/denoland/deno/issues/12577. This issue tracks the remaining issues for running [next.js](https://nextjs.org/) in deno

- [ ] `styled-jsx` detect browser env by `typeof window !== 'undefined'` (deno compat mode becomes `isBrowser: true`), then crashes after referencing `document`
- [ ] `fs.watchFs` throws uncaught error on trying to watch `next.config.mjs`
- [ ] swc binary downloader fails with `error - Failed to load SWC binary for darwin/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc`
