### ISSUE TITLE
npm compat tracking issue

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3149]
Tracking issue for npm/node compat issues in `std/node`

## High priority items
- [ ] socket option in tls.connect https://github.com/denoland/deno_std/issues/3047 (affects `npm:mssql`)
- [ ] crypto.Sign https://github.com/denoland/deno_std/issues/3006
- [ ] crypto.createSecretKey https://github.com/denoland/deno_std/issues/3097 (affects `npm:next-auth`, `npm:jsonwebtoken`)
- [ ] `npm:aws-cdk init` throws TypeError https://github.com/denoland/deno_std/issues/2916 (affects `npm:aws-cdk` (windows)

## Medium priority items
- [ ] primisify(execFile) https://github.com/denoland/deno_std/issues/3145 
- [ ] crypto.Cipheriv https://github.com/denoland/deno_std/issues/3118 (affects [tuyapi](https://github.com/codetheweb/tuyapi))
- [ ] crypto.generateKeyPairSync https://github.com/denoland/deno_std/issues/2899 (affects `npm:mineflayer`)
- [ ] missing APIs in `node:os` https://github.com/denoland/deno_std/issues/1436
- [ ] X509Certificate https://github.com/denoland/deno_std/issues/1331
- [ ] http.ClientRequest.setTimeout https://github.com/denoland/deno_std/issues/2476
- ...

#### Note about priorities

The priorities are higher when the issue affects popular npm modules (when used via `npm:` specifier).

---
#### Note to contributors

You can replace the internal node shim implementation by the command:

```shell
DENO_NODE_COMPAT_URL=file:///path/to/your/deno_std/ deno run script.ts
```

By setting `DENO_NODE_COMPAT_URL` env var, Deno uses your local deno_std/node as Node APIs, and you can test, check, or inspect the internals by modifying your local deno_std.

**Comment by iuioiua** [comment]
I'll give `crypto.createSecretKey()` a crack.

**Comment by PolarETech** [comment]
I would like to take up `promisify(execFile)`. I have already implemented `promisify(exec)`, so I think this one will be ready to go soon.

**Comment by PolarETech** [comment]
I have started to try `npm:aws-sdk init`.

Still investigating, but it seems to be an issue with `npm:fs-extra.copy()`.
Because when the function runs `fs.lstat(sourcefile)` (== `Deno.lstat(sourcefile)`) to copy the file permissions, the `mode` value is `null` on Windows. In Node.js, it is possible to get the mode value.

I will comment in that issue when the information has been compiled.

**Comment by iuioiua** [comment]
> I'll give `crypto.createSecretKey()` a crack.

I'm attempting `crypto.Sign` and `crypto.Verify` first.
