### ISSUE TITLE
Release a stable version 1.0

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno_std#3489]
- Clean ups
  - [x] denoland/deno_std#3600
  - [x] denoland/deno_std#3655
  - [x] denoland/deno_std#3601
  - [x] denoland/deno_std#3551
  - [x] denoland/deno_std#3617
  - [x] denoland/deno_std#3618
  - [x] denoland/deno_std#3549
  - [x] denoland/deno_std#3559
  - [x] denoland/deno_std#3599
  - [x] denoland/deno_std#3602
  - [x] denoland/deno_std#3616
  - [x] denoland/deno_std#3623
- Deprecations
  - [x] denoland/deno_std#3552
  - [x] denoland/deno_std#3557
  - [x] denoland/deno_std#3558
- Others
  - [x] denoland/deno_std#3562

### dependencies between std sub modules

![graphviz](https://github.com/denoland/deno_std/assets/613956/6dd5d466-a2dc-49d8-b38e-f9ab07fee1be)

- White (double circle): ready
- Yellow (circle): needs clean up
- Pink (box): not ready (needs feedback, needs re-design, too young)
- Gray (polygon): deprecated / remove

**Comment by lino-levan** [comment]
We should go over every api we offer to make sure we're not accidentally stabilizing an API that really shouldn't exist.

**Comment by jsejcksn** [comment]
Re: version `1.0`:

The readme document currently includes [this](https://github.com/denoland/deno_std/blob/0.194.0/README.md?plain=1#L11-L18):

> ## Releases
> 
> Standard library is currently tagged independently of Deno version. This will change once the library is stabilized.
> 
> To check compatibility of different version of standard library with Deno CLI see [this list](https://raw.githubusercontent.com/denoland/dotland/main/versions.json).

I interpret this to mean that the intention is to version `std` with the same version numbers as the CLI after stabilization, being released in-step. Is that interpretation accurate? Should the original statement be modified or removed?

**Comment by boywithkeyboard** [comment]
I agree with @jsejcksn that the std library should follow the versioning of Deno as shared by various Deno staff members before.

**Comment by lino-levan** [comment]
We really need to re-write `std/path` before `1.0`. That would be a blunder to leave the way it is.

**Comment by kt3k** [comment]
@lino-levan 
> We really need to re-write std/path before 1.0. That would be a blunder to leave the way it is.

Can you create an independent issue for it with more details?

**Comment by lino-levan** [comment]
I'm mainly referring to https://github.com/denoland/deno_std/issues/687. We should move to a single-file-per utility structure  as well as making OS an optional argument. I would probably do both in the same PR.

**Comment by iuioiua** [comment]
What list of things needs to be completed for v1? Also, it might be worth pinning this issue.

**Comment by lino-levan** [comment]
I'll try to triage all of the issues I see remaining into a big list of what we should resolve before 1.0 and what are just bug fixes / additions that we could do whenever.

**Comment by lino-levan** [comment]
Here's the triage I promised. I will be splitting these into three categories:
- urgent - need to decide pre 1.0 (as it fundamentally changes the structure of the project)
- non-urgent - would be a nice addition, would not require breaking changes to behavior, nice to fix
- not sure - not sure what the issue is / not sure what the impact of the changes it would entail are

If an issue isn't included, it's in the "non-urgent" category, and I had no comment to make about it (and I didn't include it to avoid unnecessarily pinging an issue). Hope this is helpful to move the standard library forward! I'll be taking a look at the APIs we provide in the near future to see if there's anything we should deprecate.

Urgent
- #678 - This would probably replace the utilities we already have
- #687 - Requires breaking changes
- #816 - Probably just needs a "no we're not doing this"
- #1136 - Maybe requires a breaking change to accomplish
- #1203 - Definitely requires a breaking change to accomplish
- #1658 - This is stuck on upstream, which is super unlucky. I'd hate to stabilize any API that relies on readers.
- #1826 - Looks like this is just a deeper sign that the logging we have right now is bad, we need to really think about this API imo.
- #1884 - Probably requires a breaking change, not sure how relevant this issue is anymore though
- #1986 - Same as #1658
- #2291 - Requires breaking changes
- #2341 - See above
- #2342 - See above
- #2370 - See above
- #2398 - Another complaint about the logging module
- #2441 - Probably need to come up with a decision on this one
- #2645 - Yet another logging complaint
- #2660
- #3018 - APIs need to be deprecated / removed
- #3538 - Another logging complaint
- #3526 - Sentiment seems mixed, we could always drop this
- #3513 - Might require breaking changes
- #3508 - Another logging complaint
- #3463 - I'm in favor of just dropping the entire folder
- #3462 - I agree in concept, but in practice it feels unlikely that this happens
- #3326 - May require breaking changes to naming
- #3394 - Another logging complaint
- #3407
- #3456 - Probably a breaking change

Not sure
- #2096
- #2147
- #2490
- #2745
- #2979
- #3268
- #3518
- #3502
- #3307

Non-Urgent
- #878 - probably a good thing to think about
- #981 - slightly out of date, probably needs some love
- #1056 - I'm gonna pick this one up
- #1070 - Probably gets resolved by https://github.com/denoland/deno/pull/19879 but I don't think that one will land
- #1126 - This should just be closed imo
- #1295 - Probably just a "no"
- #1586 - @kt3k seems to be -1 on making flags more complicated than it currently is, probably needs an update
- #1918 - would still be nice to have
- #1968 - pretty strongly against this one, we should probably make a decision
- #2204 - I'm not a fan of this one, probably just needs a "no"
- #2211 - would definitely be a "nice-to-have", though you could argue that it's out of scope. According to some good friends of mine, there aren't really any great graphQL options for Deno
- #2224 - we decided against including a redis module in the past, should this even still be open? 
- #2540 - pretty sure this is stale
- #2841 - pretty sure this should be transferred over to deno repo
- #2984 - probably stale?
- #2999 - probably stale?
- #3136 - wrong repo, should be in denobyexample
- #3231 - probably stale?
- #3250 - probably stale?
- #3279 - needs to be broken down into separate issues
- #3290 - probably needs a "no"

**Comment by kt3k** [comment]
> #1826 Looks like this is just a deeper sign that the logging we have right now is bad, we need to really think about this API imo.

I agree with this. Current logging module doesn't look good to me. We probably don't include `std/log` in the first groups of stabilization.

**Comment by guy-borderless** [comment]
> I agree with this. Current logging module doesn't look good to me. We probably don't include `std/log` in the first groups of stabilization.

I also feel the logging module can be much simplified to be less prescriptive, making it more intuitive while giving the same functionality

**Comment by kt3k** [comment]
We are planning to stabilize the following 20 sub modules in std as first pass:
- assert
- async
- bytes
- csv
- collections *
- crypto *
- encoding
- fmt
- front_matter *
- fs
- http *
- json
- jsonc
- media_types *
- path *
- streams *
- testing *
- toml
- uuid
- yaml

Note: `*` means we consider that some clean-ups are needed for stabilizing them. See issues for details. (clean-up issues for `http`, `crypto`, `testing`, `media_types` will be created soon)

We are planning to keep the below as unstable modules:
- archive
- console
- flags
- html
- log
- msgpack
- regexp
- semver
- url
- wasi

Notes:
- `console`, `html`, `msgpack`, `regexp`, and `url` are unstable because they are very new modules.
- `archive`, `flags`, `log`, and `semver` are unstable because we are not sure if the design is good enough for stabilization.
- `wasi` is unstable because we don't know if it's good idea to provide it as std module.

We are considering deprecating the below:
- datetime (overlaps with [`Temporal`](https://tc39.es/proposal-temporal/docs/) features)
- dotenv (overlaps with `--env` option of Deno CLI)
- io (We deprecate Reader/Writer related APIs)

**Comment by andrewthauer** [comment]
> dotenv (overlaps with --env option of Deno CLI)

I think the `dotenv` module is useful on its own and don't think this is a good for deprecating it. I've written a couple of CLI scripts in Deno that parse and/or generate content based on the dotenv format. Neither of these used a physical file and was purely programmatic.

**Comment by iuioiua** [comment]
In almost all cases, the dev will just want to load a dotenv file into their process. Why then, would they import a dependency to load a dotenv file into their process when such functionality is built into the runtime?

It seems you may be using dotenv files for something other than it's main use case. Perhaps, something more natural like JSON might be what you're after.

**Comment by andrewthauer** [comment]
> It seems you may be using dotenv files for something other than it's main use case. Perhaps, something more natural like JSON might be what you're after.

I'd rather not hijack this issue, but happy to converse more in a specific issue on the proposal to deprecate `dotenv`.

**Comment by cknight** [comment]
I've raised #3604 to continue the discussion on dotenv.

**Comment by jsejcksn** [comment]
> In almost all cases...

@iuioiua Claims like that need to be quantitatively substantiated. By source bytes/LOC/API surface/exports/etc., almost all of `dotenv` concerns programmatic usage.

> I'd rather not hijack this issue, but happy to converse more in a specific issue on the proposal to deprecate `dotenv`.

@andrewthauer Agree; will you please link it here when you create/discover it?

**Comment by kt3k** [comment]
@andrewthauer Thanks for the feedback. Ok, fair enough. I move `dotenv` to `unstable` category for now.

Let's keep the discussion in #3604

**Comment by iuioiua** [comment]
As discussed with Yoshiya, this issue is complete. I'm closing this in favour of #3805, which continues to build upon the work done here. Thank you to every who's helped so far!
