### ISSUE TITLE
tracking: cleanup deprecated APIs

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#3718]
Upon deprecating an API, removing its use throughout the Standard Library is best. This exposes the implications of the deprecation and is an exercise in what the migration will involve for devs using the API. I think it's best to have this done before removal to weed out any potential issues early. These are some of the deprecated APIs I've noticed that are still in use throughout the Standard Library:

- [x] [`deferred()`](https://deno.land/std@0.205.0/async/mod.ts?s=deferred) (which was deprecated in #3758)
- [x] [`BytesList()`](https://deno.land/std@0.204.0/bytes/mod.ts?s=BytesList) (to be removed in 0.205.0, but is being used in `readDelim()`, which is being removed in v1.0.0)
- [x] [`toHashString()`](https://deno.land/std@0.204.0/crypto/mod.ts?s=toHashString) (in JSDocs)
- [x] [`StringReader()`](https://deno.land/std@0.204.0/io/mod.ts?s=StringReader) (used in std/csv test, which is stable)
- [x] [`typeByExtension()`](https://deno.land/std@0.204.0/media_types/mod.ts?s=typeByExtension) (used in std/media_type, which is stable)
- [x] [`iterateReader()`](https://deno.land/std@0.204.0/streams/mod.ts?s=iterateReader) (used in std/http, which is stable)
- [x] [`readableStreamFromReader()`](https://deno.land/std@0.204.0/streams/mod.ts?s=readableStreamFromReader) (used in std/csv test, which is stable)

Note: I've done my best only to include deprecated APIs used in other stable APIs or deprecated APIs with some time till removal. Please let me know if I've missed any or included some needlessly.

**Comment by 0scvr** [comment]
I have gone through the code quickly and it seems that most of these functions are only used in deprecated functions/types (therefore not needing to be replaced) or in test files.

**Comment by iuioiua** [comment]
Yes, I've included test cases deliberately. Either way, to be sure, I double-checked my list, added reasoning behind each inclusion, and removed `readerFromIterable()` and `writeAllSync()`. Thanks for checking!

**Comment by git001** [comment]
I'm getting confused when I tak a look into `Deno.Buffer` [Deno.Buffer](https://deno.land/api@v1.37.2?s=Deno.Buffer) which links to [Buffer](https://deno.land/std@0.204.0/io/mod.ts?s=Buffer) and this mention this.

> Use Web Streams instead

I can't find the `Web Streams` in the doc. Please can be linked the `Web Streams` doc to the deprecated buffer doc, thanks.

**Comment by iuioiua** [comment]
That's a good point. I'll fix this once I get a chance.

**Comment by iuioiua** [comment]
I reviewed the list, and it appears that these deprecated APIs are no longer used in stable APIs. Work done! Thank you to those who helped.
