### ISSUE TITLE
tracking: remove use of TypeScript enums

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#3782]
The main reason is that objects align more with native JavaScript than enums. There are also other technical reasons for objects being more desirable over enums. Union types may also work, depending on the scenario.

Enums show up in the following spots:
- [x] assert/_diff.ts
- [x] console/_tools/generate_data.ts
- [x] datetime/week_of_year.ts
- [x] fmt/printf.ts
- [x] fs/eol.ts
- [x] http/http_status.ts and http/status.ts (see #3781)
- [x] jsonc/parse.ts
- [x] log/levels.ts
- [x] toml/stringify.ts

Note: the `enum`s in front_matter/_format.ts  and archive/_common.ts are deliberately omitted as the corresponding implementations will soon be deprecated.

References:
- https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums
- https://youtu.be/jjMbPt_H3RQ?feature=shared
- https://youtu.be/3aUHskjF7pc?feature=shared

**Comment by Nkiriobasi** [comment]
Has this been fixed? if not, can I fix it.

**Comment by iuioiua** [comment]
Great! Yep, it's still available. Would you like me to assign you?

**Comment by Nkiriobasi** [comment]
Yes

**Comment by realpha** [comment]
hi, is this is still open? (Seems to be without assignee). Could I take a stab at this?

Would it be possible to convert the tasks into individual issues or would you prefer to just reference the tracking issue in the individual prs?

**Comment by iuioiua** [comment]
Best that we tackle them in separate PRs and reference this issue.
