### ISSUE TITLE
tracking: complete `std/expct`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#3964]
The following APIs are currently not yet implemented in `std/expect`:

- [ ] `toMatchSnapShot`
- [ ] `toMatchInlineSnapShot`
- [ ] `toThrowErrorMatchingSnapShot`
- [ ] `toThrowErrorMatchingInlineSnapShot`
- [ ] `expect.anything`
- [ ] `expect.any`
- [ ] `expect.arrayContaining`
- [ ] `expect.not.arrayContaining`
- [ ] `expect.closedTo`
- [ ] `expect.objectContaining`
- [ ] `expect.not.objectContaining`
- [ ] `expect.stringContaining`
- [ ] `expect.not.stringContaining`
- [ ] `expect.stringMatching`
- [ ] `expect.not.stringMatching`
- [ ] `expect.assertions`
- [ ] `expect.hasAssertions`
- [ ] `expect.addEqualityTester`
- [ ] `expect.addSnapshotSerializer`
- [ ] `expect.extend`

For those wanting to contribute, please submit one PR per API.

**Comment by raashidanwar** [comment]
Hey @iuioiua, 
I would love to contribute here.

**Comment by iuioiua** [comment]
> Hey @iuioiua, 
> 
> I would love to contribute here.

Great! Let us know which ones you'd like to work on, so there's no overlap with other's work.

**Comment by syhol** [comment]
As you start working on the async matchers, you might end up fixing https://github.com/denoland/deno_std/issues/3947 as a side effect.

**Comment by raashidanwar** [comment]
@iuioiua I will be picking.
```
expect.objectContaining
expect.not.objectContaining
expect.stringContaining
expect.not.stringContaining
expect.stringMatching
expect.not.stringMatching
```

**Comment by eryue0220** [comment]
Hi @iuioiua @raashidanwar 
Can I try for this too?

I'll pick

```ts
expect.assertions
expect.hasAssertions
expect.addSnapshotSerializer
expect.extend
```

**Comment by iuioiua** [comment]
> Hi @iuioiua @raashidanwar Can I try for this too?
> 
> I'll pick
> 
> ```ts
> expect.assertions
> expect.hasAssertions
> expect.addSnapshotSerializer
> expect.extend
> ```

For sure! Thank you. Please let us know if you need any help with anything.

**Comment by eryue0220** [comment]
Hi, @iuioiua 

I have a question about is there a way that I can know whether the current `Deno.test` is completed or not?

**Comment by iuioiua** [comment]
Can you elaborate? Perhaps, something like this is what you're after.
```ts
let isTestDone = false;
Deno.test("my test", () => {
  ...
  isTestDone = true;
});
```

**Comment by eryue0220** [comment]
> Can you elaborate? Perhaps, something like this is what you're after.
> 
> ```ts
> let isTestDone = false;
> Deno.test("my test", () => {
>   ...
>   isTestDone = true;
> });
> ```

Oh, sorry ~

What I mean that is there any methods that know the `callback` is done as for the `Deno.test('test', callback)`? If use a variable is a little tricky I think, because someone may write code like:

And `expect.hasAssertions` API is want to check if there were any assertions executed before, for example:

```ts
Deno.test('test suite', () => {
  expect.hasAssertion();
});
```

this will throw an error, there was no any assertions in test suite function at all . And the following code will pass:

```ts
Deno.test('test suite', () => {
    expect.hasAssertions();
    expect(1 + 2).toEqual(3);
});
```

On the other hand, why I know current test suite function is done or not, thus can throw an error exactly when the test suite function is completed.

**Comment by eryue0220** [comment]
> I don't think we have such hook in `Deno.test`. These are the current options of Deno.test https://deno.land/api@v1.40.2?s=Deno.TestDefinition

Is there any possibility to add some similar hook in `deno_core`, such as `before` and `after`?

**Comment by kt3k** [comment]
> Is there any possibility to add some similar hook in deno_core, such as before and after?

Not sure if we are still open to such addition. When the last time we discussed similar topic, we decided to add test steps (See https://docs.deno.com/runtime/manual/basics/testing/#test-steps ). That essentially added hook capability to `deno test`.

So maybe it's a bit unlikely we add another hook capability to deno test, but I'm not completely sure.

**Comment by kt3k** [comment]
It might be non ideal, but maybe we can add support of `expect.hasAssertions()` only for `describe` `it` runners. They are wrappers of `Deno.test` and `t.step`, and we can add arbitrary hooks before and after it.

**Comment by eryue0220** [comment]
> > Is there any possibility to add some similar hook in deno_core, such as before and after?
> 
> Not sure if we are still open to such addition. When the last time we discussed similar topic, we decided to add test steps (See https://docs.deno.com/runtime/manual/basics/testing/#test-steps ). That essentially added hook capability to `deno test`.
> 
> So maybe it's a bit unlikely we add another hook capability to deno test, but I'm not completely sure.

Thanks for the information, but I think it's still not same as I mentioned before. Because `t.step` requires every developer to write their own assertion logic if they want to use `expect.hasAssertion` API. Or it will not work if use the api only.

**Comment by eryue0220** [comment]
> It might be non ideal, but maybe we can add support of `expect.hasAssertions()` only for `describe` `it` runners. They are wrappers of `Deno.test` and `t.step`, and we can add arbitrary hooks before and after it.这可能并不理想，但也许我们可以仅为 `describe` `it` 跑步者添加 `expect.hasAssertions()` 的支持。它们是 `Deno.test` 和 `t.step` 的包装器，我们可以在其前后添加任意钩子。

It's also a good option, and can combine with [deno_lint](https://github.com/denoland/deno_lint) to do some limits.

**Comment by javihernant** [comment]
I'd like to work on:
expect.anything
expect.any
expect.arrayContaining
expect.not.arrayContaining

**Comment by timreichen** [comment]
Just out of interest: here the methods are called `*Containing` while native array api has `includes` and the assert mod uses `*Includes` . Is this intentional?

**Comment by iuioiua** [comment]
For anyone wanting to contribute, we also need to make the [`Expected` interface](https://github.com/denoland/deno_std/blob/8b90e3154cb24783f50b5b60b2c7a68127ad6e88/expect/_types.ts#L44C18-L44C26) public (it's currently private) and include documentation, with examples, for each method.

**Comment by iuioiua** [comment]
@kt3k, is [`fn()`](https://github.com/denoland/deno_std/blob/8b90e3154cb24783f50b5b60b2c7a68127ad6e88/expect/fn.ts#L7C17-L7C19) supposed to be part of the public API?

**Comment by kt3k** [comment]
Yes, it corresponds to `jest.fn` https://jestjs.io/docs/mock-functions

**Comment by finleyjb** [comment]
I'm considering implementing `objectContaining`. Is anyone working on this?

**Comment by eryue0220** [comment]
> I'm considering implementing `objectContaining`. Is anyone working on this?

Yes, I'm doing this now. You could try other API.

**Comment by rperryng** [comment]
> Yes, it corresponds to jest.fn [jestjs.io/docs/mock-functions](https://jestjs.io/docs/mock-functions)

on that note, are there plans to improve the type-safety around `fn()` to match the type-safety of `jest.fn()`?

> ```typescript
>   // Create a new mock that can be used in place of `add`.
>   const mockAdd = jest.fn<typeof add>();
> 
>   // `.mockImplementation()` now can infer that `a` and `b` are `number`
>   // and that the returned value is a `number`.
>   mockAdd.mockImplementation((a, b) => {
>     // Yes, this mock is still adding two numbers but imagine this
>     // was a complex function we are mocking.
>     return a + b;
>   });
> ```
>
> _([`jest.fn()` docs](https://jestjs.io/docs/mock-function-api#jestfnimplementation))_

Since `fn()` currently is typed as `Function`, it returns `any` (which the [typescript docs](https://www.typescriptlang.org/docs/handbook/2/functions.html#function) mention as a reason to avoid its usage).

(I hope this is the right place for this conversation, I couldn't find any other open issues that cover this topic yet)

**Comment by WWRS** [comment]
I can implement `toMatchSnapshot` and `toThrowErrorMatchingSnapshot`, but I want to see how dependencies change in #6541 before starting.

Same for `toMatchInlineSnapshot` and `toThrowErrorMatchingInlineSnapshot`, but I am also waiting on #6530.
