### ISSUE TITLE
todo: fix tests after workspaces migration script is run

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4346]
I've yet to investigate this properly. I am putting this here in case someone can get to it before me. To fix:
1. Run the migration script using `deno run -A _tools/convert_to_workspace.ts`.
2. Run `deno task test`.
3. Fix any test failures.
4. Submit a PR of the fixes, excluding the migration script changes.

**Comment by kt3k** [comment]
- [ ] ./assert/_format_test.ts
- [ ] ./crypto/crypto_test.ts:169:6
- [ ] digest() keeps memory usage reasonable with many calls => ./crypto/crypto_test.ts:251:6
- [ ] KeyStack() handles inspection => ./crypto/unstable_keystack_test.ts:225:6
- [ ] format() overrides default behaviours of Deno.inspect ... format() wraps Object with getters => ./expect/_format_test.ts:43:11
- [ ] format() doesn't truncate long strings in object => ./expect/_format_test.ts:89:6
- [ ] sprintf() handles formatV => ./fmt/printf_test.ts:620:6
- [ ] sprintf() handles lessThan flag => ./fmt/printf_test.ts:666:6
- [ ] sprintf() handles errors => ./fmt/printf_test.ts:677:6
- [ ] emptyDir() test ("testdata/testfolder") without --allow-read & without --allow-write permission => ./fs/empty_dir_test.ts:192:8
- [ ] emptyDirSync() test ("testdata/testfolder") without --allow-read & without --allow-write permission => ./fs/empty_dir_test.ts:192:8
- [ ] emptyDir() test ("testdata/testfolder") with --allow-read & without --allow-write permission => ./fs/empty_dir_test.ts:192:8
- [ ] emptyDirSync() test ("testdata/testfolder") with --allow-read & without --allow-write permission => ./fs/empty_dir_test.ts:192:8
- [ ] emptyDir() test ("testdata/testfolder") without --allow-read & with --allow-write permission => ./fs/empty_dir_test.ts:192:8
- [ ] emptyDirSync() test ("testdata/testfolder") without --allow-read & with --allow-write permission => ./fs/empty_dir_test.ts:192:8
- [ ] emptyDir() test ("testdata/testfolder") with --allow-read & with --allow-write permission => ./fs/empty_dir_test.ts:192:8
- [ ] emptyDirSync() test ("testdata/testfolder") with --allow-read & with --allow-write permission => ./fs/empty_dir_test.ts:192:8
- [ ] expandGlob() throws permission error without fs permissions => ./fs/expand_glob_test.ts:235:6
- [ ] serveDir() script prints help => ./http/file_server_test.ts:340:6
- [ ] serveDir() script prints version => ./http/file_server_test.ts:357:6
- [ ] serveDir() script fails with partial TLS args => ./http/file_server_test.ts:384:6
- [ ] Server should not close the http2 downstream connection when the response stream throws => ./http/server_test.ts:1123:6
- [ ] ./http/server_test.ts (uncaught error)
- [ ] warnDeprecatedApi() => ./internal/warn_on_deprecated_api_test.ts:5:6

**Comment by iuioiua** [comment]
This has been completed in the above PRs.
