### ISSUE TITLE
todo: investigate use of `CAN_NOT_DISPLAY` constant

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#4699]
We need to determine whether the use of this constant is actually warranted. It's been found in:
- [x] `assert/assert_equals.ts`
- [x] `assert/assert_not_equals.ts`
- [x] `assert/assert_strict_equals.ts`
- [x] `expect/_build_message.ts`
