### ISSUE TITLE
to-do: investigate the viability of `ParseOptions` and `StringifyOptions` in `@std/yaml`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#5195]
These interfaces have a lot of options, and each added option means more engineering overhead for both users and maintainers. We should go over each option and only keep the ones that have sufficient justifications for existing.

[`ParseOptions`](https://jsr.io/@std/yaml/doc/parse/~/ParseOptions):
- [x] [`legacy`](https://jsr.io/@std/yaml/doc/parse/~/ParseOptions.legacy) (removed in #5229)
- [x] [`listener`](https://jsr.io/@std/yaml/doc/parse/~/ParseOptions.listener) (removed in #5224)
- [x] [`filename`](https://jsr.io/@std/yaml/doc/parse/~/ParseOptions.filename) (removed in #5223)
- [x] [`schema`](https://jsr.io/@std/yaml/doc/parse/~/ParseOptions.schema)
- [ ] [`json`](https://jsr.io/@std/yaml/doc/parse/~/ParseOptions.json) (renamed to `allowDuplicateKeys` in #5282)
- [x] [`onWarning`](https://jsr.io/@std/yaml/doc/parse/~/ParseOptions.onWarning) (reworked in #5284)

[`StringifyOptions`](https://jsr.io/@std/yaml/doc/~/DumpOptions) (currently `DumpOptions` but to be updated in the next release):
- [ ] [`indent`](https://jsr.io/@std/yaml/doc/~/DumpOptions.indent)
- [ ] [`noArrayIndent`](https://jsr.io/@std/yaml/doc/~/DumpOptions.noArrayIndent)
- [ ] [`skipInvalid`](https://jsr.io/@std/yaml/doc/~/DumpOptions.skipInvalid)
- [ ] [`flowLevel`](https://jsr.io/@std/yaml/doc/~/DumpOptions.flowLevel)
- [ ] [`styles`](https://jsr.io/@std/yaml/doc/~/DumpOptions.styles)
- [x] [`schema`](https://jsr.io/@std/yaml/doc/~/DumpOptions.schema)
- [ ] [`sortKeys`](https://jsr.io/@std/yaml/doc/~/DumpOptions.sortKeys)
- [ ] [`lineWidth`](https://jsr.io/@std/yaml/doc/~/DumpOptions.lineWidth)
- [ ] [`noRefs`](https://jsr.io/@std/yaml/doc/~/DumpOptions.noRefs)
- [ ] [`noCompatMode`](https://jsr.io/@std/yaml/doc/~/DumpOptions.noCompatMode) (removed in #5233)
- [ ] [`condenseFlow`](https://jsr.io/@std/yaml/doc/~/DumpOptions.condenseFlow)

**Comment by iuioiua** [comment]
`ParseOptions.json` allows `parse()` to behave similarly to `JSON.parse()`, in that duplicate keys are overwritten rather than throwing errors. This goes against the YAML 1.2 spec, which states that duplicate keys should cause errors (see [here](https://yaml.org/spec/1.2.2/#mapping) and [here](https://yaml.org/spec/1.2.2/#node-comparison)). Do we want to remove the ability to have this functionality (AKA remove `ParseOptions.json`) or keep it? @kt3k

**Comment by iuioiua** [comment]
This has been completed in a series of already merged PRs.
